### PR TITLE
i did some stuff

### PR DESCRIPTION
**Pull request by 7ih**
here i will explain some thingies

- most of the new code is to fix/improve code or make the interaction between mouse and touchscreen seamless (i can do this cuz my laptop comes with a touchscreen)
- game can now be paused while pointer is locked. pausing is also objectively improved
- the title screen now comes with a "click to start" (or tap if on touchscreen) because pointer lock sometimes only works with a click
- some of the new code in the animate function kinda sucks sorry lol, u can improve it if u feel like it since im too lazy

if i ever do another pull request, it will be for fullscreen support (no guarantees though)

### CODE REVIEW

**Review by rayhanadev — APPROVED** [review]
I trust that you have checked everything and it works fine :). Again thank's working on this game so much I really appreciate it!

**Comment by 7ih** [comment]
i tested it for 10 minutes and checked everything, it should be fine (i hope), and you're welcome for the help!

**Comment by rayhanadev** [comment]
@7ih maybe just me on mobile but if I load the game it says 'undefined to start': https://tether.rayhanadev.repl.co/source/

**Comment by rayhanadev** [comment]
After clicking it says tap to start. Could be we need a preset of some kind?

**Comment by rayhanadev** [comment]
Did a change on line 1926 just added a fallback.

**Comment by rayhanadev** [comment]
Did it on several other places as well.

**Comment by rayhanadev** [comment]
Lastly I reimplemented the pause message as a prototype of the `Game()` so that it actually works :D. https://tether.rayhanadev.repl.co/source/

**Comment by rayhanadev** [comment]
I'll minify this down and put it on the main site.

**Comment by 7ih** [comment]
i actually noticed that but forgot to fix it lol, all the gameplay stuff should work tho

**Comment by rayhanadev** [comment]
@7ih it does, thanks!

**Pull request merged**
